// <auto-generated />
using System;
using DamascusComplaintSystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DamascusComplaintSystem.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612065954_SeedComplaintTypes")]
    partial class SeedComplaintTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DamascusComplaintSystem.Api.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CadastralZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplaintRepeatCount")
                        .HasColumnType("int");

                    b.Property<string>("ComplaintText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplaintTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParcelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PreviousComplaintDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousComplaintNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyLocationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintTypeId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("DamascusComplaintSystem.Api.Models.ComplaintType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComplaintTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicName = "مخالفة بناء",
                            Name = "BuildingViolation"
                        },
                        new
                        {
                            Id = 2,
                            ArabicName = "ممارسة مهنة بدون ترخيص",
                            Name = "UnlicensedProfession"
                        },
                        new
                        {
                            Id = 3,
                            ArabicName = "شخصية",
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 4,
                            ArabicName = "عقارية",
                            Name = "RealEstate"
                        },
                        new
                        {
                            Id = 5,
                            ArabicName = "التعدي على أملاك العامة",
                            Name = "PublicPropertyViolation"
                        },
                        new
                        {
                            Id = 6,
                            ArabicName = "إشغال رصيف",
                            Name = "SidewalkOccupation"
                        });
                });

            modelBuilder.Entity("DamascusComplaintSystem.Api.Models.Complaint", b =>
                {
                    b.HasOne("DamascusComplaintSystem.Api.Models.ComplaintType", "ComplaintType")
                        .WithMany()
                        .HasForeignKey("ComplaintTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplaintType");
                });
#pragma warning restore 612, 618
        }
    }
}
